# Generated by Django 5.0 on 2024-09-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('apellidos_y_nombres', models.CharField(max_length=255)),
                ('carrera_primera_opcion', models.CharField(max_length=255)),
                ('puntaje', models.FloatField(blank=True, null=True)),
                ('merito', models.CharField(blank=True, max_length=255, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('carrera_segunda_opcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.CharField(blank=True, max_length=255, null=True)),
                ('modalidad_de_ingreso', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
