# Generated by Django 5.0 on 2024-09-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('apellidos_y_nombres', models.CharField(max_length=255)),
                ('carrera_primera_opcion', models.CharField(max_length=255)),
                ('puntaje', models.FloatField(null=True)),
                ('merito', models.CharField(blank=True, max_length=255, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('carrera_segunda_opcion', models.CharField(blank=True, max_length=255, null=True)),
                ('source_url', models.URLField(default='unkown')),
            ],
        ),
    ]
