# Generated by Django 5.0 on 2024-09-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='source_url',
        ),
        migrations.AddField(
            model_name='person',
            name='fecha',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='modalidad_de_ingreso',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='codigo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='puntaje',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
