# Generated by Django 5.0 on 2024-09-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='source_url',
            field=models.URLField(default='unkown'),
        ),
    ]
