# Generated by Django 5.0 on 2024-09-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_remove_person_source_url_person_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='fecha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='modalidad_de_ingreso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
